import datetime

data = datetime.date.today()
data_formatada = data.strftime("%d/%m/%Y")  # Formato dd/mm/aaaa
# formulário de ficha de protudo e cliente
print('#'*100)
tec = str(input('Técnico Responsável: '))
cliente = str(input('Digite o nome do cliente: '))
#data = str(input('digite dia, mes e ano: '))
produto = str(input('Digite o nome do produto: '))
serie = str(input('Digite o numero de serie: '))
estadoproduto = str(input('Digite o estado do produto: '))
itensdoproduto = str(input('Digite os itens do produto: '))
defeitoreclamado = str(input('Digite o defeito reclamado: '))
defeitoencontrado = str(input('Digite o defeito encontrado: '))
rpt = str(input('Digite os Itens trocados: '))
print('#'*100)
print(f'#### Cliente: {cliente}      Data: {data_formatada}      Produto: {produto}')
print(f'#### Itens do Produto: {itensdoproduto}')
print(f'#### Estado do Produto: {estadoproduto}')
print('#'*100)
print(f'#### Defeito Reclamado: {defeitoreclamado}')
print(f'#### Defeito Encontrado: {defeitoencontrado}')
print('#'*100)
print(f'#### Relatório de Peças Trocadas: {rpt}')
print('#'*100)
print('')
print(f'#### Técnico Responsável: {tec}')
