# formulário de ficha de protudo e cliente

cliente = str(input('Digite o nome do cliente: '))
data = str(input('digite dia, mes e ano: '))
produto = str(input('Digite o nome do produto: '))
serie = str(input('Digite o numero de serie: '))
estadoproduto = str(input('Digite o estado do produto: '))
itensdoproduto = str(input('Digite os itens do produto: '))
defeitoreclamado = str(input('Digite o defeito reclamado: '))
defeitoencontrado = str(input('Digite o defeito encontrado: '))
print('#'*100)
print(f'Cliente: {cliente}      Data: {data}      Produto: {produto}')
print(f'Itens do Produto: {itensdoproduto}')
print(f'Estado do Produto: {estadoproduto}')
print("")
print('#'*100)